version: '3.8'
name: advent-of-code
services:
  php-apache:
    container_name: php-apache
    build:
      dockerfile: dockerfile
    volumes:
      - ../:/var/www/html/
      - ./php:/usr/local/etc/php
    ports:
      - "8080:80"
