FROM php:8.4.15-cli-alpine3.22

# Composer - https://getcomposer.org/download/
ENV COMPOSER_VERSION="2.8.12"
ENV COMPOSER_SHA256="f446ea719708bb85fcbf4ef18def5d0515f1f9b4d703f6d820c9c1656e10a2f2"

# Install composer
RUN set -eux \
    && curl -LO "https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar" \
    && echo "${COMPOSER_SHA256} composer.phar" | sha256sum -c - \
    && chmod +x composer.phar \
    && mv composer.phar /usr/local/bin/composer

RUN set -eux \
\
    ## Dependencies
    # Persistent
        && apk add --no-cache \
            gmp \
    # Build
        && apk add --no-cache --virtual .build-deps \
            $PHPIZE_DEPS \
            binutils \
            linux-headers \
            gmp-dev \
\
    ## Extensions
    # GMP
        && docker-php-ext-install gmp \
    # Xdebug
        && pecl install -o xdebug \
        && docker-php-ext-enable xdebug \
    # Strip symbols
        && (find /usr/local/lib/php/extensions -type f -name "xdebug.so" -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
\
    # Cleanup
    && apk del .build-deps

ENV PHP_IDE_CONFIG serverName=AoC-docker

WORKDIR /app
