FROM php:8.4-cli-alpine

ARG COMPOSER_VERSION="2.8.3"
ARG COMPOSER_SUM="8323b4105c6e166d47c9db93209370083f9e421743636e108c37d8c1126386ef"

RUN set -eux \
\
    ## Dependencies
    # Persistent
        && apk add --no-cache \
            gmp \
    # Build
        && apk add --no-cache --virtual .build-deps \
            $PHPIZE_DEPS \
            binutils \
            linux-headers \
            gmp-dev \
\
    ## Extensions
    # GMP
        && docker-php-ext-install gmp \
    # Xdebug
        && pecl install -o xdebug \
        && docker-php-ext-enable xdebug \
\
    # Composer
        && curl -LO "https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar" \
        && echo "${COMPOSER_SUM}  composer.phar" | sha256sum -c - \
        && chmod +x composer.phar \
        && mv composer.phar /usr/local/bin/composer \
\
    # Shrink binaries
        && (find /usr/local/bin -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
        && (find /usr/local/lib -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
        && (find /usr/local/sbin -type f -print0 | xargs -n1 -0 strip --strip-all -p 2>/dev/null || true) \
\
    # Cleanup
    && apk del .build-deps

ENV PHP_IDE_CONFIG serverName=AoC-docker
ENV PHP_CS_FIXER_IGNORE_ENV 1

WORKDIR /app
